# docker-compose -f ./docker/docker-compose-test.yaml up --build
# docker-compose -f ./docker/docker-compose-test.yaml down

version: "2.4"
x-net:
  &net
  networks:
    - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    container_name: workflow-calcium-imaging-ccn2023-db
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  workflow:
    <<: *net
    build:
      context: ../../
      dockerfile: ./workflow-calcium-imaging/docker/Dockerfile
    image: workflow-calcium-imaging-ccn2023:1.0.0
    container_name: workflow-calcium-imaging-ccn2023
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
      - IMAGING_ROOT_DATA_DIR=/main/test_data
      - DATABASE_PREFIX=ccn2023_
    command:
      - bash
      - -c
      - |
        echo "------ INTEGRATION TESTS ------"
        pytest -sv --cov-report term-missing --cov=workflow_calcium_imaging -p no:warnings
        tail -f /dev/null
    volumes:
      - ${TEST_DATA_DIR}:/main/test_data
      - ..:/main/workflow-calcium-imaging
    depends_on:
      db:
        condition: service_healthy
networks:
  main:
