# docker-compose -f ./docker/docker-compose-test.yaml up --build
# docker-compose -f ./docker/docker-compose-test.yaml down

version: "2.4"
x-net:
  &net
  networks:
    - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    container_name: workflow-calcium-imaging-test-db
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  workflow:
    <<: *net
    build:
      context: ../../
      dockerfile: ./workflow-calcium-imaging/docker/Dockerfile.test
    image: workflow-calcium-imaging-test:0.1.0a2
    container_name: workflow-calcium-imaging-test
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
      - IMAGING_ROOT_DATA_DIR=/main/test_data
      - DATABASE_PREFIX=test_
    command:
      - bash
      - -c
      - |
        echo "------ INTEGRATION TESTS ------"
        pytest -sv --cov-report term-missing --cov=workflow_calcium_imaging -p no:warnings
        tail -f /dev/null
    volumes:
      - ${TEST_DATA_DIR}:/main/test_data
      - ./apt_requirements.txt:/tmp/apt_requirements.txt
      - ../../element-lab:/main/element-lab
      - ../../element-animal:/main/element-animal
      - ../../element-session:/main/element-session
      - ../../element-interface:/main/element-interface
      - ../../element-calcium-imaging:/main/element-calcium-imaging
      - ..:/main/workflow-calcium-imaging
    depends_on:
      db:
        condition: service_healthy
networks:
  main:
